"""collatro.package — save results as JSON + Markdown."""

import hashlib
import json
from datetime import datetime, timezone, timedelta
from pathlib import Path

from src.config import OUTPUT_DIR

TZ = timezone(timedelta(hours=8))


def _slug(text: str) -> str:
    return hashlib.sha256(text.encode()).hexdigest()[:8]


def package(text: str, claims: list[dict], enrich_result: dict | None = None) -> dict:
    """Assemble final output package."""
    now = datetime.now(TZ)
    return {
        "slug": _slug(text),
        "timestamp": now.isoformat(),
        "text": text,
        "claims": claims,
        "enrich": enrich_result,
        "summary": {
            "total_claims": len(claims),
            "mismatch": sum(1 for c in claims if c.get("diff", {}).get("verdict") == "mismatch"),
            "match": sum(1 for c in claims if c.get("diff", {}).get("verdict") == "match"),
            "insufficient": sum(1 for c in claims if c.get("diff", {}).get("verdict") == "insufficient"),
        },
    }


def save(pkg: dict, output_dir: str = None) -> Path:
    """Save package as JSON + MD. Returns MD path."""
    out = Path(output_dir) if output_dir else OUTPUT_DIR
    out.mkdir(exist_ok=True)
    stem = f"{pkg['slug']}_{pkg['timestamp'][:19].replace(':','').replace('-','')}"

    # JSON
    json_path = out / f"{stem}.json"
    json_path.write_text(json.dumps(pkg, ensure_ascii=False, indent=2), encoding="utf-8")

    # Markdown
    md = _render_md(pkg)
    md_path = out / f"{stem}.md"
    md_path.write_text(md, encoding="utf-8")

    return md_path


def _render_md(pkg: dict) -> str:
    lines = [f"# 事實比對：{pkg['text'][:50]}…\n"]
    lines.append(f"## 原始文字\n\n{pkg['text']}\n")

    # Enrich
    enrich = pkg.get("enrich")
    if enrich and enrich.get("entities"):
        lines.append("## 實體背景\n")
        for e in enrich["entities"]:
            if e.get("found"):
                lines.append(f"- **{e['name']}**: {e.get('description','')} ([Wikipedia]({e.get('wiki_url','')}))")
        lines.append("")

    # Claims
    lines.append("## 主張比對\n")
    lines.append("| # | 主張 | 判定 | 差異 |")
    lines.append("|---|------|------|------|")
    for i, c in enumerate(pkg.get("claims", []), 1):
        diff = c.get("diff", {})
        verdict = diff.get("verdict", "?")
        icon = {"match": "✓", "mismatch": "✗", "insufficient": "？"}.get(verdict, "？")
        diffs = []
        for d in diff.get("ner", []):
            diffs.append(f"NER: {d.get('claim_says','')} → {d.get('evidence_says','')}")
        for d in diff.get("numbers", []):
            diffs.append(f"數字: {d.get('claim_says','')} → {d.get('evidence_says','')}")
        for d in diff.get("timeline", []):
            diffs.append(f"時間: {d.get('claim_says','')} → {d.get('evidence_says','')}")
        diff_str = "; ".join(diffs) if diffs else "—"
        lines.append(f"| {i} | {c.get('text','')[:40]} | {icon} {verdict} | {diff_str[:60]} |")

    lines.append(f"\n---\n*Generated by Collatro at {pkg['timestamp']}*")
    return "\n".join(lines)
